name: Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Clean up existing Docker installations
      run: |
        sudo apt-get remove -y containerd.io docker docker-engine docker.io containerd runc
        sudo apt-get autoremove -y
        sudo apt-get update

    - name: Install Docker
      run: |
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: SSH and Deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
      run: |
        echo "$SSH_PRIVATE_KEY" > key.pem
        chmod 400 key.pem
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${EC2_PUBLIC_IP} << 'EOF'
          cd /home/ec2-user/trial_task
          git pull origin main
          docker-compose down
          docker-compose up -d --build
          docker-compose exec -T web python manage.py migrate
        EOF
